name: Validate changes

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
  JIRA_PAT: ${{ secrets.JIRA_PAT }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno task check

      - name: Validate changes
        run: deno task validate

      - name: Validate All
        run: deno task validate-all

      - name: Check spellings
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_file: .codespellignore
          path: data

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Save changes
        if: steps.branch-name.outputs.is_default == 'false'
        run: deno task save

      - name: Sync changes
        if: steps.branch-name.outputs.is_default == 'false'
        run: deno task sync

      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   if: steps.branch-name.outputs.is_default == 'false'
      #   with:
      #     commit_message: "chore(data): Sync"
      #     create_branch: true
      #     branch: data-sync
      #     add_options: '-u'
      #     skip_dirty_check: true
      #     commit_user_name: mattermost-quality
      #     commit_user_email: qa@mattermost.com


      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash