name: Validate changes

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
  JIRA_PAT: ${{ secrets.JIRA_PAT }}
  EMAIL: ${{ secrets.EMAIL }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno task check

      - name: Validate changes
        run: deno task validate

      - name: Validate All
        run: deno task validate-all

      - name: Check spellings
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_file: .codespellignore
          path: data

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Save changes
        if: steps.branch-name.outputs.is_default == 'false'
        run: deno task save

      - name: Sync changes
        if: steps.branch-name.outputs.is_default == 'false'
        run: deno task sync

      - name: Create PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            npm install @octokit/rest
            const title = "chore(data): Sync";
            const body = "Syncing changes from Zephyr";
            const head = "sync-branch";
            const base = "main";
            const octokit = require("@octokit/rest")();
            octokit.authenticate({
              type: "token",
              token: process.env.GITHUB_TOKEN,
            });
            const { data: pr } = await octokit.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base,
            });
            console.log(`Created PR #${pr.number}: ${pr.html_url}`);

    
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   if: steps.branch-name.outputs.is_default == 'true'
      #   with:
      #     commit_message: "chore(data): Sync"
      #     add_options: '-u'
      #     skip_dirty_check: true
      #     commit_user_name: mattermost-quality
      #     commit_user_email: ${{ secrets.EMAIL }}

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     signoff: false
      #     title: Sync updates
      #     body: "**Pull request to update data from Zephyr**"
      #     draft: false
      #     commit-message: 'chore(data): Sync'
      #     committer: Mattermost Quality <qa@mattermost.com>
      #     author: Mattermost Quality <qa@mattermost.com>
      #     base: main
      #     branch: data-sync
      #     delete-branch: true
